name: Laravel Pint
on:
  pull_request:
    branches:
      - master
    paths:
      - '**.php'
  push:
    branches:
      - master
    paths:
      - '**.php'
jobs:
  Laravel-Pint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Run Composer
        run: composer install

      - name: Run Laravel Pint
        run: ./vendor/bin/pint -v

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Laravel Pint changes
