name: Laravel Pint
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.php'
  push:
    branches:
      - main
    paths:
      - '**.php'
jobs:
  Laravel-Pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Composer
        run: composer install

      - name: Run Laravel Pint
        run: ./vendor/bin/pint -v

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Laravel Pint changes
